# Generated by Django 4.2.5 on 2023-10-18 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("image", models.ImageField(blank=True, upload_to="images/")),
                ("slug", models.SlugField(max_length=250, unique_for_date="publish")),
                ("body", models.TextField()),
                ("publish", models.DateTimeField(default=django.utils.timezone.now)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("DF", "DRAFT"), ("PB", "PUBLISHED")],
                        default="DF",
                        max_length=2,
                    ),
                ),
            ],
            options={
                "ordering": ["-publish"],
            },
        ),
    ]
