# Generated by Django 4.2.5 on 2023-09-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
